# In-memory session state stores
TEMP_RESULTS = {}
FINAL_RESULTS = {}
MUSIC_QUEUE = {}
USER_SELECTIONS = {}
GAME_QUEUE = {}
READY_PLAYLISTS = {}
ANALYTICS_QUEUE = {}
ANALYTICS_RESULTS = {}
MAL_IMPORT_QUEUE = {}
